---
- hosts: web
  tasks:
    - name: ensure nginx is at the latest version
      yum: 
         name: nginx 
         state: latest
         update_cache: true
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx index html file 
      copy:
        src: /home/marakkannu/Downloads/work/ansible/index.html
        dest: /usr/share/doc/HTML/index.html
      become: yes      